import type { GetStaticProps, InferGetStaticPropsType, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { ReactElement } from "react";
import Layout from "../components/layout";
import PostItemCard from "../components/post-item-card";
import { useAuth } from "../context/auth";
import { adminDb } from "../firebase/server";
import styles from "../styles/Home.module.css";
import { Post } from "../types/post";
import { NextPageWithLayout } from "./_app";

export const getStaticProps: GetStaticProps<{
    posts: Post[];
}> = async (context) => {
    const snap = await adminDb
        .collection("posts")
        .orderBy("createdAt", "desc")
        .get();
    const posts = snap.docs.map((doc) => doc.data() as Post);

    return {
        props: {
            posts: posts,
        },
    };
};

const Home: NextPageWithLayout<
    InferGetStaticPropsType<typeof getStaticProps>
> = ({ posts }) => {
    const { user } = useAuth();
    console.log(user);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h2>最新の記事</h2>
                {posts?.length ? (
                    <ul className="space-y-3">
                        {posts?.map((post: Post) => (
                            <li key={post.id}>
                                <PostItemCard post={post} />
                            </li>
                        ))}
                    </ul>
                ) : (
                    <p>記事がありません。</p>
                )}
            </main>
        </div>
    );
};

Home.getLayout = function getLayout(page: ReactElement) {
    return <Layout>{page}</Layout>;
};

export default Home;
